#include <gtest/gtest.h>

#include <fstream>
#include <nlohmann/json.hpp>
#include <set>
#include <string>
#include <vector>

#include "tokenizer/byte_level_bpe_tokenizer.h"

// Tokenizer alignment test: compares ccInfer's simplified byte-level BPE
// tokenizer against HuggingFace reference data.
//
// Reference JSON is generated by:
//   python scripts/generate_tokenizer_reference.py --tokenizer <path>/tokenizer.json
//
// Known limitations (pre_tokenizer regex granularity — not HF-exact):
//   prompts containing complex punctuation / code fences / HTML-like tags
//   may differ from HF token ids.  These are excluded from strict comparison
//   but verified for encode→decode roundtrip correctness.

namespace {

#ifndef REFERENCE_PATH
#define REFERENCE_PATH "tests/unit/tokenizer_alignment_reference.json"
#endif
std::string kReferencePath = REFERENCE_PATH;

// Prompts excluded from strict token-id comparison due to known
// pre_tokenizer regex limitations.  They are verified for roundtrip instead.
const std::set<std::string> kKnownLimitationPrompts = {
    "template <typename T>\nResult<void> foo(T x) {\n    return {};\n}",
    "```cpp\nint x = 42;\n```",
    "<s>Hello</s>",
};

std::string ids_to_string(const std::vector<int32_t>& ids) {
    std::string s = "[";
    for (size_t i = 0; i < ids.size(); ++i) {
        if (i) s += ", ";
        s += std::to_string(ids[i]);
    }
    s += "]";
    return s;
}

}  // namespace

class TokenizerAlignmentTest : public ::testing::Test {
protected:
    void SetUp() override {
        std::ifstream f(kReferencePath);
        if (!f.is_open()) {
            GTEST_SKIP() << "Reference file not found: " << kReferencePath
                         << "\n  Run: python scripts/generate_tokenizer_reference.py"
                         << " --tokenizer <path>/tokenizer.json";
        }
        reference_ = nlohmann::json::parse(f);
        tokenizer_path_ = reference_.value("tokenizer_path", "");
        ASSERT_FALSE(tokenizer_path_.empty()) << "Reference missing tokenizer_path";

        auto r = tokenizer_.load(tokenizer_path_);
        ASSERT_TRUE(r) << "Failed to load tokenizer: " << tokenizer_path_;
    }

    bool is_known_limitation(const std::string& prompt) const {
        return kKnownLimitationPrompts.count(prompt) > 0;
    }

    ccinfer::ByteLevelBpeTokenizer tokenizer_;
    nlohmann::json reference_;
    std::string tokenizer_path_;
};

TEST_F(TokenizerAlignmentTest, VocabSize) {
    EXPECT_EQ(tokenizer_.vocab_size(), reference_["vocab_size"].get<int32_t>());
}

TEST_F(TokenizerAlignmentTest, EncodeNoSpecial) {
    int failures = 0;
    int skipped = 0;
    for (const auto& c : reference_["cases"]) {
        std::string prompt = c["prompt"].get<std::string>();
        if (is_known_limitation(prompt)) {
            ++skipped;
            continue;
        }
        std::vector<int32_t> expected = c["encode_no_special"].get<std::vector<int32_t>>();

        auto our_r = tokenizer_.encode(prompt, false);
        ASSERT_TRUE(our_r) << "encode failed for: " << prompt;

        if (*our_r != expected) {
            ADD_FAILURE() << "MISMATCH encode(add_special_tokens=false)\n"
                          << "  prompt: " << prompt << "\n"
                          << "  expected(" << expected.size() << "): "
                          << ids_to_string(expected) << "\n"
                          << "  ours   (" << our_r->size() << "): "
                          << ids_to_string(*our_r);
            ++failures;
        }
    }
    if (skipped > 0) {
        std::cout << "  [KNOWN LIMITATIONS] " << skipped
                  << " prompts skipped (pre_tokenizer regex — see test file comments)\n";
    }
    EXPECT_EQ(failures, 0) << failures << " encode(add_special_tokens=false) mismatches";
}

TEST_F(TokenizerAlignmentTest, EncodeSpecial) {
    int failures = 0;
    int skipped = 0;
    for (const auto& c : reference_["cases"]) {
        std::string prompt = c["prompt"].get<std::string>();
        if (is_known_limitation(prompt)) {
            ++skipped;
            continue;
        }
        std::vector<int32_t> expected = c["encode_special"].get<std::vector<int32_t>>();

        auto our_r = tokenizer_.encode(prompt, true);
        ASSERT_TRUE(our_r) << "encode failed for: " << prompt;

        if (*our_r != expected) {
            ADD_FAILURE() << "MISMATCH encode(add_special_tokens=true)\n"
                          << "  prompt: " << prompt << "\n"
                          << "  expected(" << expected.size() << "): "
                          << ids_to_string(expected) << "\n"
                          << "  ours   (" << our_r->size() << "): "
                          << ids_to_string(*our_r);
            ++failures;
        }
    }
    EXPECT_EQ(failures, 0) << failures << " encode(add_special_tokens=true) mismatches";
}

TEST_F(TokenizerAlignmentTest, DecodeSkipSpecial) {
    int failures = 0;
    for (const auto& c : reference_["cases"]) {
        std::string prompt = c["prompt"].get<std::string>();
        auto ids = c["encode_no_special"].get<std::vector<int32_t>>();
        std::string expected = c["decode_no_special"].get<std::string>();

        auto our_r = tokenizer_.decode(ids, true);
        ASSERT_TRUE(our_r) << "decode failed for: " << prompt;

        if (*our_r != expected) {
            ADD_FAILURE() << "MISMATCH decode(skip_special_tokens=true)\n"
                          << "  prompt: " << prompt << "\n"
                          << "  expected: " << expected << "\n"
                          << "  ours   : " << *our_r;
            ++failures;
        }
    }
    EXPECT_EQ(failures, 0) << failures << " decode mismatches";
}

// Known-limitation prompts must still roundtrip: encode → decode restores text.
TEST_F(TokenizerAlignmentTest, KnownLimitationRoundtrip) {
    for (const auto& c : reference_["cases"]) {
        std::string prompt = c["prompt"].get<std::string>();
        if (!is_known_limitation(prompt)) continue;

        auto our_r = tokenizer_.encode(prompt, false);
        ASSERT_TRUE(our_r) << "encode failed for known-limitation prompt: " << prompt;

        auto dec_r = tokenizer_.decode(*our_r, true);
        ASSERT_TRUE(dec_r) << "decode failed for known-limitation prompt: " << prompt;

        EXPECT_EQ(*dec_r, prompt)
            << "ROUNDTRIP MISMATCH for known-limitation prompt.\n"
            << "  original: " << prompt << "\n"
            << "  roundtrip: " << *dec_r << "\n"
            << "  token ids (" << our_r->size() << "): " << ids_to_string(*our_r);
    }
}
